# version: '3.9'

services:
  postgres:
    image: postgres:15  # Versão do PostgreSQL
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # Mapeia a porta local 5432 para a porta do container
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
